# cmake/sources.cmake

function(micro_aac_get_sources FAAC_DIR HELIX_DIR)
    set(FAAC_SOURCES
        "${FAAC_DIR}/libfaac/bitstream.c"
        "${FAAC_DIR}/libfaac/blockswitch.c"
        "${FAAC_DIR}/libfaac/channels.c"
        "${FAAC_DIR}/libfaac/cpu_compute.c"
        "${FAAC_DIR}/libfaac/faac.c"
        "${FAAC_DIR}/libfaac/filtbank.c"
        "${FAAC_DIR}/libfaac/fft.c"
        "${FAAC_DIR}/libfaac/frame.c"
        "${FAAC_DIR}/libfaac/huff2.c"
        "${FAAC_DIR}/libfaac/huffdata.c"
        "${FAAC_DIR}/libfaac/quantize.c"
        "${FAAC_DIR}/libfaac/ratecontrol.c"
        "${FAAC_DIR}/libfaac/sbr.c"
        "${FAAC_DIR}/libfaac/sbr_bitstream.c"
        "${FAAC_DIR}/libfaac/sbr_tables.c"
        "${FAAC_DIR}/libfaac/sbr_analysis.c"
        "${FAAC_DIR}/libfaac/resample.c"
        "${FAAC_DIR}/libfaac/stereo.c"
        "${FAAC_DIR}/libfaac/tns.c"
        "${FAAC_DIR}/libfaac/util.c"
        PARENT_SCOPE
    )

    set(HELIX_AAC_SOURCES
        "${HELIX_DIR}/src/libhelix-aac/aacdec.c"
        "${HELIX_DIR}/src/libhelix-aac/aactabs.c"
        "${CMAKE_CURRENT_SOURCE_DIR}/src/helix_aac/helix_bitstream.c"
        "${HELIX_DIR}/src/libhelix-aac/buffers.c"
        "${HELIX_DIR}/src/libhelix-aac/dct4.c"
        "${HELIX_DIR}/src/libhelix-aac/decelmnt.c"
        "${HELIX_DIR}/src/libhelix-aac/dequant.c"
        "${CMAKE_CURRENT_SOURCE_DIR}/src/helix_aac/helix_fft.c"
        "${HELIX_DIR}/src/libhelix-aac/filefmt.c"
        "${HELIX_DIR}/src/libhelix-aac/huffman.c"
        "${HELIX_DIR}/src/libhelix-aac/hufftabs.c"
        "${HELIX_DIR}/src/libhelix-aac/imdct.c"
        "${HELIX_DIR}/src/libhelix-aac/noiseless.c"
        "${HELIX_DIR}/src/libhelix-aac/pns.c"
        "${CMAKE_CURRENT_SOURCE_DIR}/src/helix_aac/helix_sbr.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrfft.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrfreq.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrhfadj.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrhfgen.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrhuff.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrimdct.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrmath.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrqmf.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrside.c"
        "${HELIX_DIR}/src/libhelix-aac/sbrtabs.c"
        "${HELIX_DIR}/src/libhelix-aac/stproc.c"
        "${CMAKE_CURRENT_SOURCE_DIR}/src/helix_aac/helix_tns.c"
        "${HELIX_DIR}/src/libhelix-aac/trigtabs.c"
        "${HELIX_DIR}/src/utils/helix_memory.cpp"
        PARENT_SCOPE
    )

    set(WRAPPER_SOURCES
        "${CMAKE_CURRENT_SOURCE_DIR}/src/aac_encoder.cpp"
        "${CMAKE_CURRENT_SOURCE_DIR}/src/aac_decoder.cpp"
        PARENT_SCOPE
    )
endfunction()
