# cmake/sources.cmake

function(micro_aac_get_sources FAAC_DIR HELIX_DIR)
    set(FAAC_SOURCES
        "lib/faac/libfaac/bitstream.c"
        "lib/faac/libfaac/blockswitch.c"
        "lib/faac/libfaac/channels.c"
        "lib/faac/libfaac/cpu_compute.c"
        "lib/faac/libfaac/faac.c"
        "lib/faac/libfaac/filtbank.c"
        "lib/faac/libfaac/fft.c"
        "lib/faac/libfaac/frame.c"
        "lib/faac/libfaac/huff2.c"
        "lib/faac/libfaac/huffdata.c"
        "lib/faac/libfaac/quantize.c"
        "lib/faac/libfaac/ratecontrol.c"
        "lib/faac/libfaac/sbr.c"
        "lib/faac/libfaac/sbr_bitstream.c"
        "lib/faac/libfaac/sbr_tables.c"
        "lib/faac/libfaac/sbr_analysis.c"
        "lib/faac/libfaac/resample.c"
        "lib/faac/libfaac/stereo.c"
        "lib/faac/libfaac/tns.c"
        "lib/faac/libfaac/util.c"
        PARENT_SCOPE
    )

    set(HELIX_AAC_SOURCES
        "lib/helix-aac/src/libhelix-aac/aacdec.c"
        "lib/helix-aac/src/libhelix-aac/aactabs.c"
        "lib/helix-aac/src/libhelix-aac/bitstream.c"
        "lib/helix-aac/src/libhelix-aac/buffers.c"
        "lib/helix-aac/src/libhelix-aac/dct4.c"
        "lib/helix-aac/src/libhelix-aac/decelmnt.c"
        "lib/helix-aac/src/libhelix-aac/dequant.c"
        "lib/helix-aac/src/libhelix-aac/fft.c"
        "lib/helix-aac/src/libhelix-aac/filefmt.c"
        "lib/helix-aac/src/libhelix-aac/huffman.c"
        "lib/helix-aac/src/libhelix-aac/hufftabs.c"
        "lib/helix-aac/src/libhelix-aac/imdct.c"
        "lib/helix-aac/src/libhelix-aac/noiseless.c"
        "lib/helix-aac/src/libhelix-aac/pns.c"
        "lib/helix-aac/src/libhelix-aac/sbr.c"
        "lib/helix-aac/src/libhelix-aac/sbrfft.c"
        "lib/helix-aac/src/libhelix-aac/sbrfreq.c"
        "lib/helix-aac/src/libhelix-aac/sbrhfadj.c"
        "lib/helix-aac/src/libhelix-aac/sbrhfgen.c"
        "lib/helix-aac/src/libhelix-aac/sbrhuff.c"
        "lib/helix-aac/src/libhelix-aac/sbrimdct.c"
        "lib/helix-aac/src/libhelix-aac/sbrmath.c"
        "lib/helix-aac/src/libhelix-aac/sbrqmf.c"
        "lib/helix-aac/src/libhelix-aac/sbrside.c"
        "lib/helix-aac/src/libhelix-aac/sbrtabs.c"
        "lib/helix-aac/src/libhelix-aac/stproc.c"
        "lib/helix-aac/src/libhelix-aac/tns.c"
        "lib/helix-aac/src/libhelix-aac/trigtabs.c"
        "lib/helix-aac/src/utils/helix_memory.cpp"
        PARENT_SCOPE
    )

    set(WRAPPER_SOURCES
        "src/aac_encoder.cpp"
        "src/aac_decoder.cpp"
        PARENT_SCOPE
    )
endfunction()
